"""add foreign key indices

Revision ID: 873c0c4616ea
Revises: 1b0b616e08c6
Create Date: 2023-08-15 23:10:01.739927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "873c0c4616ea"
down_revision = "1b0b616e08c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_conversationdocument_conversation_id"),
        "conversationdocument",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversationdocument_document_id"),
        "conversationdocument",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_conversation_id"), "message", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_messagesubprocess_message_id"),
        "messagesubprocess",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_messagesubprocess_message_id"), table_name="messagesubprocess"
    )
    op.drop_index(op.f("ix_message_conversation_id"), table_name="message")
    op.drop_index(
        op.f("ix_conversationdocument_document_id"), table_name="conversationdocument"
    )
    op.drop_index(
        op.f("ix_conversationdocument_conversation_id"),
        table_name="conversationdocument",
    )
    # ### end Alembic commands ###
