"""update sub process columns

Revision ID: c008bb4f3f48
Revises: 477cee72edc4
Create Date: 2023-07-07 18:11:35.087271

"""
from typing import Set
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c008bb4f3f48"
down_revision = "477cee72edc4"
branch_labels = None
depends_on = None

existing_sub_process_source_enum_values = {
    "CHUNKING",
    "NODE_PARSING",
    "EMBEDDING",
    "LLM",
    "QUERY",
    "RETRIEVE",
    "SYNTHESIZE",
    "TREE",
    "CONSTRUCTED_QUERY_ENGINE",
}

new_sub_process_source_enum_values = {
    *existing_sub_process_source_enum_values,
    "SUB_QUESTIONS",
}


def replace_enum_values(enum_name: str, table: str, new_values: Set[str]):
    """
    Create a new type, add the value to it, update the column to use the new type and delete the old type
    """
    op.execute(f'ALTER TYPE public."{enum_name}" RENAME TO "{enum_name}Old"')
    sa.Enum(*new_values, name=enum_name).create(op.get_bind())
    op.execute(
        f'ALTER TABLE {table} ALTER COLUMN source TYPE public."{enum_name}" USING source::text::public."{enum_name}"'
    )
    op.execute(f'DROP TYPE public."{enum_name}Old"')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM("PENDING", "FINISHED", name="MessageSubProcessStatusEnum")
    enum.create(op.get_bind())
    op.add_column(
        "messagesubprocess",
        sa.Column("status", enum, nullable=False, server_default="FINISHED"),
    )
    op.add_column(
        "messagesubprocess",
        sa.Column(
            "metadata_map", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("messagesubprocess", "content")

    # Alter MessageSubProcessEnum to add "SUB_QUESTIONS" as a valid value
    replace_enum_values(
        "MessageSubProcessSourceEnum",
        "messagesubprocess",
        new_sub_process_source_enum_values,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # revert back to the old enum type
    # Note that this won't work if the DB already has rows with the new enum values
    replace_enum_values(
        "MessageSubProcessSourceEnum",
        "messagesubprocess",
        existing_sub_process_source_enum_values,
    )

    op.add_column(
        "messagesubprocess",
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("messagesubprocess", "metadata_map")
    op.drop_column("messagesubprocess", "status")
    # ### end Alembic commands ###
