"""cascade commit

Revision ID: ee73fc803704
Revises: 663b3fea3024
Create Date: 2023-12-03 18:44:07.577117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee73fc803704'
down_revision: Union[str, None] = '663b3fea3024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversationdocument_document_id_fkey', 'conversationdocument', type_='foreignkey')
    op.drop_constraint('conversationdocument_conversation_id_fkey', 'conversationdocument', type_='foreignkey')
    op.create_foreign_key(None, 'conversationdocument', 'document', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversationdocument', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('message_conversation_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messagesubprocess_message_id_fkey', 'messagesubprocess', type_='foreignkey')
    op.create_foreign_key(None, 'messagesubprocess', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messagesubprocess', type_='foreignkey')
    op.create_foreign_key('messagesubprocess_message_id_fkey', 'messagesubprocess', 'message', ['message_id'], ['id'])
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_conversation_id_fkey', 'message', 'conversation', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'conversationdocument', type_='foreignkey')
    op.drop_constraint(None, 'conversationdocument', type_='foreignkey')
    op.create_foreign_key('conversationdocument_conversation_id_fkey', 'conversationdocument', 'conversation', ['conversation_id'], ['id'])
    op.create_foreign_key('conversationdocument_document_id_fkey', 'conversationdocument', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
